# traefik.yml (static) â€” enables plugin & applies middleware chain globally on websecure
entryPoints:
  websecure:
    address: ":443"
    http:
      middlewares:
        - sn-chain@file

providers:
  docker: {}
  file:
    filename: /etc/traefik/dynamic/sn-dynamic.yml

experimental:
  plugins:
    rewritebody:
      moduleName: "github.com/traefik/plugin-rewritebody"
      version: "v0.3.1"
