global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - '/etc/prometheus/alert_rules.yml'

scrape_configs:
  - job_name: 'traefik'
    static_configs: [{ targets: ['traefik:8080'] }]
  - job_name: 'prometheus'
    static_configs: [{ targets: ['prometheus:9090'] }]
  - job_name: 'node-exporter'
    static_configs: [{ targets: ['node-exporter:9100'] }]
  - job_name: 'cadvisor'
    static_configs: [{ targets: ['cadvisor:8080'] }]
  - job_name: 'blackbox-exporter'
    static_configs: [{ targets: ['blackbox:9115'] }]
  - job_name: 'loki'
    static_configs: [{ targets: ['loki:3100'] }]
  - job_name: 'redis'
    static_configs: [{ targets: ['redis-exporter:9121'] }]
  - job_name: 'postgres'
    static_configs: [{ targets: ['postgres-exporter:9187'] }]
  - job_name: 'headscale'
    static_configs: [{ targets: ['headscale:9090'] }]
  - job_name: 'authentik'
    static_configs: [{ targets: ['authentik_server:9300'] }]
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params: { module: [http_2xx] }
    static_configs:
      - targets: [ "https://authentik.${DOMAIN}", "https://grafana.${DOMAIN}", "https://${DOMAIN}" ]
    relabel_configs:
      - { source_labels: [__address__], target_label: __param_target }
      - { target_label: __address__, replacement: blackbox:9115 }
      - { source_labels: [__param_target], target_label: instance }
  - job_name: 'blackbox-smtp'
    metrics_path: /probe
    params: { module: [smtp_starttls] }
    static_configs:
      - targets: [ "mail.${DOMAIN}:587" ]
    relabel_configs:
      - { source_labels: [__address__], target_label: __param_target }
      - { target_label: __address__, replacement: blackbox:9115 }
      - { source_labels: [__param_target], target_label: instance }
  - job_name: 'coredns'
    static_configs:
      - targets: ['coredns:9153']
  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']
  - job_name: 'blackbox-dns'
    metrics_path: /probe
    params:
      module: [dns_soa]
    static_configs:
      - targets:
          - "8.8.8.8:53"      # Google DNS
          - "1.1.1.1:53"      # Cloudflare DNS
          - "208.67.222.222:53" # OpenDNS
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        replacement: securenexus.net
      - source_labels: [__address__]
        target_label: __param_module
        replacement: dns_soa
      - source_labels: [__address__]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

