# ========== SYSLOG / AUTH LOGS ==========
---
filenames:
  - /var/log/auth.log
  - /var/log/syslog
labels:
  type: syslog

# ========== DOCKER (CADDY) LOGS ==========
---
source: docker
container_name:
  - caddy-main
labels:
  type: docker
